NightTime: 120
DiscussionTime: 300
InfoScoreBoardName: "OneNightJinro"
NoticeComingOut: true
spawnpoint:
  world:
  x:
  y:
  z:
  yaw:
  pitch:
reikai:
  world:
  x:
  y:
  z:
  yaw:
  pitch:

Debug: false