name: Prog
version: ${project.version}
main: mckd.me.prog.Prog
authors: [nankotsu029]
groups:
  default:
    permissions:
      - modifyworld.*
    options:
      default: true
  Jinro.GameMaster:
    options:
      default: false
    permissions:
      - '*'



  Jinro.Spectator:
    description: Spectator
    default: false
  J
commands:
  jinro:
    description: Player
    permission: Jinro.Player
    usage: 一般向けのコマンドやで だれでも使えるやで
  jinro_ad:
    description: GameMaster
    permission: Jinro.GameMaster
    usage: GM向けのコマンドやで 一般会員は使えないやで
  c:
    description: 指定役職全体通知
    permission: Jinro.GameMaster
    usage: GM向けやで