name: Prog
version: ${project.version}
main: mckd.me.prog.Prog
authors: [nankotsu029]




commands:
  count:
    description: TimerCommand
  playingBuild:
    description: test
  sendTitle:
    description: test
  allGamemode:
    description: test